### ISSUE TITLE
can replace fastpath with iptables with action NOTRACK?(是否可以用iptables notrack的方式替换fastpath)

### ISSUE THREAD

**Issue by jiawentao83** [kubeovn/kube-ovn#1363]
rules in raw table of iptables can assign notrack action，notrack means skip contrack/nat.  it has the same function with fastpath, Is this method feasible ?
for example geneve:  iptables -t raw -A PREROUTING -d dest_ip -p udp--dport 6081 -j NOTRACK

**Comment by oilbeater** [comment]
We have test the `NOTRACK` action before and it only has subtle improvement. The reason is that the `NOTRACK` action only skip the conntrack system which is only a small part of netfilter, packet still has to go through heavy netfilter hooks like ipvs/iptables/nftables etc. And as packet in container has to go through both container netns netfilter and host netns, the burden doubled.  The fastpaht moudule hook at the beginning of netfilter and skip all the subsequent hooks in both netns which can lead the performance boost. 

You can try the iptables rules in your cluster and use perf to draw the flamegraph and you will see the difference
